name: Publish

on:
  push:
    tags:
      - 'v*'   # run publish only on version tags like v1.0.0
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  cross-compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - x86_64-unknown-linux-gnu
          - x86_64-linux-android
          - i686-unknown-linux-musl
          - i686-unknown-linux-gnu
          - i686-linux-android
          - armv7-unknown-linux-musleabihf
          - armv7-unknown-linux-gnueabihf
          - arm-linux-androideabi
          - aarch64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - aarch64-linux-android

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust (stable 1.93)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-1.93
          profile: minimal
          override: true

      - name: Install cargo-make
        run: cargo install cargo-make

      - name: Install cross
        run: cargo install cross --version 0.2.1

      - name: Build pronyx
        run: |
          cross build --release --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pronyx-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/pronyx

      - name: Compress binaries for release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ARCHIVE=pronyx-${{ github.ref_name }}-${{ matrix.target }}.tar.gz
          tar czvf $ARCHIVE -C target/${{ matrix.target }}/release pronyx

      - name: Upload binaries to GitHub release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: pronyx-${{ github.ref_name }}-${{ matrix.target }}.tar.gz
          asset_name: pronyx-rs-${{ github.ref_name }}-${{ matrix.target }}.tar.gz
          tag: ${{ github.ref_name }}